name: Python CI

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
        shell: pwsh

      - name: Lint with ruff
        run: |
          ruff format --check .
          ruff check .
        shell: pwsh

      - name: Type check with pyright
        run: pyright src/run_hy8
        shell: pwsh

      - name: Test with pytest and generate coverage
        run: pytest --cov=src/run_hy8 --cov-report=xml
        shell: pwsh